### ISSUE TITLE
Participation in edison-fw community project

### ISSUE THREAD

**Issue by andy-shev** [Kudesnick/ed_666#2]
I'm just wondering if you consider participating in https://github.com/edison-fw project.

**Comment by Kudesnick** [comment]
I would like to participate, but at the moment my qualifications are not enough. Your articles on a habr helped me a lot. I was able to build and run the vanilla core and modify the u-boot a bit. However, I never managed to collect an image with support for the BT gamepad from PS3. Yocto turned out to be too complex a build system for me.

**Comment by andy-shev** [comment]
Okay, maybe "participating" is too strong word, what I meant is to try it and contribute to it. But I got your point.

P.S. I guess @htot has a really good Wiki pages regarding to the project and he answered a lot of similar questions about Yocto already.

**Comment by htot** [comment]
The instructions here https://edison-fw.github.io/meta-intel-edison/ should help you build an image, and if not I welcome suggestions for improvement (or better patches to the docs/).

The wiki from here https://edison.internet-share.com is now relocated here https://edison-fw.github.io/edison-wiki/.

**Comment by Kudesnick** [comment]
Thank you fo the links. I think it really helps me.
